BLO-4370 Allow build architecture selection

diff --git a/.github/workflows/template_gitops.yml b/.github/workflows/template_gitops.yml
--- a/.github/workflows/template_gitops.yml
+++ b/.github/workflows/template_gitops.yml
@@ -17,6 +17,11 @@ on:
         required: false
         type: string
         description: "Custom output destinations for docker build (e.g., type=registry,push=true,compression=gzip,force-compression=true). Required for DHI images."
+      docker-build-platform:
+        required: false
+        type: string
+        description: "A build platform (e.g., linux/amd64, linux/arm64). If multiple platforms are specified, the action will fail as it does not support cross-compilation."
+        default: "linux/amd64"
       docker-build-provenance:
         required: false
         type: string
@@ -68,6 +73,10 @@ on:
         required: false
         type: string
         default: "ubuntu-24.04"
+      runs-on-arm:
+        required: false
+        type: string
+        default: "ubuntu-24.04-arm"
       upwind-organization-id:
         required: false
         type: string
@@ -97,9 +106,28 @@ on:
         required: false
 
 jobs:
+  check-single-platform:
+    name: Single Platform Check
+    runs-on: ubuntu-slim
+    steps:
+      - name: Check if only a single platform is built
+        id: check_single_platform
+        run: |
+          platform="${{ inputs.docker-build-platform }}"
+          platform_count=$(echo "$platform" | tr ',' '\n' | wc -l)
+          if [ "$platform_count" -gt 1 ]; then
+              echo "Multiple platforms are built: ${platform}"
+              echo "::error::This action only supports one platform and no cross compiling."
+              exit 1
+          else
+              echo "Only a single platform is built: ${platform}"
+          fi
+
+
   gitops:
-    name: GitOps
-    runs-on: ${{ inputs.runs-on }}
+    name: GitOps (${{ inputs.docker-build-platform }})
+    needs: check-single-platform
+    runs-on: ${{ inputs.docker-build-platform == 'linux/arm64' && inputs.runs-on-arm || inputs.runs-on }}
     if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
 
     env:
@@ -120,7 +148,7 @@ jobs:
 
       - name: GitOps (build, push and deploy a new Docker image)
         id: gitops
-        uses: Staffbase/gitops-github-action@v6.5
+        uses: Staffbase/gitops-github-action@v6.6
         with:
           docker-registry: ${{ inputs.docker-registry }}
           docker-username: ${{ secrets.docker-username }}
@@ -132,6 +160,7 @@ jobs:
           docker-build-secret-files: ${{ secrets.docker-build-secret-files }}
           docker-build-target: ${{ inputs.docker-build-target }}
           docker-build-outputs: ${{ inputs.docker-build-outputs }}
+          docker-build-platforms: ${{ matrix.platform }}
           docker-build-provenance: ${{ inputs.docker-build-provenance }}
           docker-disable-retagging: ${{ inputs.docker-disable-retagging }}
           docker-file: ${{ inputs.docker-file }}
